# ./docker-compose.yml
version: "3"
services:
  bot:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8888:5000"
    env_file:
     - proxy.env
    restart: always
    command: [sh, -c, yarn && yarn build && yarn start]
networks:
  default:
    external:
      name: shared
